# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #CAE2F4
background         #16161E
cursor             #CAE2F4

active_tab_foreground     #16161E
active_tab_background     #CAE2F4
inactive_tab_foreground   #CAE2F4
inactive_tab_background   #16161E

active_border_color   #CAE2F4
inactive_border_color #16161E
bell_border_color     #030F2B

color0      #3D3D46
color1		#030F2B
color2		#2C4A80
color3		#325587
color4		#6D689B
color5		#4C7EA4
color6		#4E81A7
color7		#ABCDE6
color8		#7890A1
color9		#04143A
color10		#3A63AB
color11		#4371B5
color12		#918ACF
color13		#65A8DB
color14		#68ACDE
color15		#ABCDE6
